language: node_js

node_js:
  - "12"

variables:
  DENO_VERSION: "v0.31.0"

install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh -s $DENO_VERSION
  - deno --version
  - export PATH="$HOME/.deno/bin:$PATH"

script:
  - deno test --allow-all .
